controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


contact:
    path: /contact
    controller: App\Controller\ContactController::contactAction

contact_save:
    path: /contact/save
    controller: App\Controller\ContactController::saveAction